server:
  port: 9999
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql:///ssh_2?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.java.entity
  mapper-locations: mapper/*.xml